artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/alfandysurya2/project_datasets/raw/main/TextSummarizerDatasets/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_files: ['train', 'test', 'validation']